const OWNER='ATritle',REPO='tkleaderboard',BRANCH='main',INCIDENT_FILE='data/teamkills.json',PLAYER_FILE='data/players.json',API_BASE=`https://api.github.com/repos/${OWNER}/${REPO}`;
const $=id=>document.getElementById(id),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),clean=s=>String(s??'').trim().replace(/\s+/g,' ');
let incidents=[],players=[],editing=null;
let playerImages=[];

async function loadPlayerImages(){
  const select=$('playerImage');
  if(!select)return;
  try{
    const r=await fetch(`data/player-images.json?v=${Date.now()}`);
    if(!r.ok)throw Error(`HTTP ${r.status}`);
    const data=await r.json();
    playerImages=Array.isArray(data)?data.map(x=>String(x).trim()).filter(Boolean):[];
    select.innerHTML='<option value="">No Image</option>'+
      playerImages.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');
    updatePlayerImagePreview();
  }catch(e){
    console.error('Could not load player-images.json:',e);
    status('playerStatus','Could not load player image list.','error');
  }
}

function imagePath(filename){
  if(!filename)return '';
  if(/^https?:\/\//i.test(filename))return filename;
  return `assets/${filename}`;
}

function updatePlayerImagePreview(){
  const select=$('playerImage'),img=$('playerImagePreview'),empty=$('playerImageEmpty');
  if(!select||!img||!empty)return;
  const filename=select.value;
  if(!filename){
    img.removeAttribute('src');img.classList.remove('visible');empty.style.display='flex';return;
  }
  img.src=imagePath(filename);img.classList.add('visible');empty.style.display='none';
  img.onerror=()=>{img.classList.remove('visible');empty.style.display='flex';empty.textContent='IMAGE NOT FOUND';};
  img.onload=()=>{empty.style.display='none';img.classList.add('visible');};
}

function status(id,msg,type='show'){const e=$(id);e.textContent=msg;e.className=`status show ${type}`}function clearStatus(id){$(id).textContent='';$(id).className='status'}function token(){return $('token').value.trim()}function headers(auth=false){const h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(auth)h.Authorization=`Bearer ${token()}`;return h}
function dec(c){const d=atob(c.replace(/\n/g,''));return JSON.parse(new TextDecoder().decode(Uint8Array.from(d,c=>c.charCodeAt(0))))}function enc(x){const b=new TextEncoder().encode(JSON.stringify(x,null,2)+'\n');let s='';for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)}
async function read(path){const r=await fetch(`${API_BASE}/contents/${path}?ref=${BRANCH}&t=${Date.now()}`,{headers:headers()});if(!r.ok)throw Error(`Could not read ${path} (HTTP ${r.status}).`);const j=await r.json();return{sha:j.sha,data:dec(j.content)}}
function normalizePlayers(data){const raw=Array.isArray(data)?data:[];return[...new Map(raw.map(x=>typeof x==='string'?[norm(x),{name:clean(x),image:''}]:[norm(x?.name),{name:clean(x?.name),image:String(x?.image??'').trim()}]).filter(([k,p])=>k&&p.name)).values()].sort((a,b)=>a.name.localeCompare(b.name))}
async function load(){try{const[a,b]=await Promise.all([read(INCIDENT_FILE),read(PLAYER_FILE)]);incidents=Array.isArray(a.data)?a.data:[];players=normalizePlayers(b.data);populate();renderPlayers();renderRecent()}catch(e){status('playerStatus',e.message,'error')}}
function populate(){$('killer').innerHTML='<option value="">Select player...</option>'+players.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')}
function renderPlayers(){if(!players.length){$('playerList').innerHTML='<div class="player-empty">No players have been added yet.</div>';return}$('playerList').innerHTML=players.map((p,i)=>`<div class="player-row player-row-image"><span class="player-number">${String(i+1).padStart(2,'0')}</span>${p.image?`<img class="player-avatar-small" src="${esc(imagePath(p.image))}" alt="" onerror="this.style.display='none'">`:'<span class="player-avatar-placeholder">?</span>'}<div class="player-info"><strong>${esc(p.name)}</strong><span class="player-usage">${incidents.some(x=>norm(x.killer)===norm(p.name))?'IN TK HISTORY':'NO TKs YET'}</span></div><button class="edit-player" data-player="${esc(p.name)}">EDIT</button><button class="remove-player" data-player="${esc(p.name)}">REMOVE</button></div>`).join('');document.querySelectorAll('.edit-player').forEach(b=>b.onclick=()=>editPlayer(b.dataset.player));document.querySelectorAll('.remove-player').forEach(b=>b.onclick=()=>removePlayer(b.dataset.player))}
function editPlayer(name){const p=players.find(x=>norm(x.name)===norm(name));if(!p)return;editing=norm(p.name);$('newPlayer').value=p.name;$('playerImage').value=p.image||'';updatePlayerImagePreview();$('addPlayer').textContent='SAVE PLAYER';clearStatus('playerStatus');$('newPlayer').focus()}function cancelEdit(){editing=null;$('newPlayer').value='';$('playerImage').value='';updatePlayerImagePreview();$('addPlayer').textContent='✚   ADD PLAYER'}
async function savePlayers(list,msg){if(!token()){status('playerStatus','Enter your GitHub token first.','error');$('token').focus();return false}const r=await fetch(`${API_BASE}/contents/${PLAYER_FILE}?ref=${BRANCH}&t=${Date.now()}`,{headers:headers(true)});if(!r.ok)throw Error(`GitHub roster read failed (HTTP ${r.status}).`);const cur=await r.json();const put=await fetch(`${API_BASE}/contents/${PLAYER_FILE}`,{method:'PUT',headers:{...headers(true),'Content-Type':'application/json'},body:JSON.stringify({message:msg,content:enc(list.map(p=>({name:p.name,image:p.image||''}))),sha:cur.sha,branch:BRANCH})});const j=await put.json();if(!put.ok)throw Error(j.message||'GitHub roster update failed.');players=normalizePlayers(list);populate();renderPlayers();return true}
async function addPlayer(){const name=clean($('newPlayer').value),image=$('playerImage').value.trim();if(!name)return status('playerStatus','Enter a player name.','error');try{if(editing){if(players.some(p=>norm(p.name)===norm(name)&&norm(p.name)!==editing))return status('playerStatus','Another player already has that name.','error');const list=players.map(p=>norm(p.name)===editing?{name,image}:p);status('playerStatus',`Saving ${name}...`,'working');if(await savePlayers(list,`Update player: ${name}`)){cancelEdit();status('playerStatus',`${name} updated successfully.`,'success')}return}if(players.some(p=>norm(p.name)===norm(name)))return status('playerStatus',`${players.find(p=>norm(p.name)===norm(name)).name} is already on the roster. Use EDIT to change the image.`,'error');status('playerStatus',`Adding ${name}...`,'working');if(await savePlayers([...players,{name,image}],`Add player: ${name}`)){$('newPlayer').value='';$('playerImage').value='';updatePlayerImagePreview();status('playerStatus',`${name} added successfully.`,'success')}}catch(e){status('playerStatus',e.message,'error')}}
async function removePlayer(name){if(!confirm(`Remove "${name}" from the player roster?\n\nExisting TK history will not be deleted.`))return;try{status('playerStatus',`Removing ${name}...`,'working');if(await savePlayers(players.filter(p=>norm(p.name)!==norm(name)),`Remove player: ${name}`))status('playerStatus',`${name} removed. Existing incidents were not changed.`,'success')}catch(e){status('playerStatus',e.message,'error')}}
function nextId(a){return`TK-${String(a.reduce((n,i)=>Math.max(n,Number(String(i.id||'').replace(/^TK-/i,''))||0),0)+1).padStart(4,'0')}`}function recent(){return[...incidents].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id))).slice(0,10)}
function renderRecent(){$('adminRecent').innerHTML=`<div class="table-head"><span>TK ID</span><span>KILLER</span><span>VICTIM</span><span>DATE</span><span>MAP</span><span>NOTES</span><span>CLIP</span><span>ACTION</span></div>`+recent().map(i=>`<div class="incident-row"><span class="tkid">${esc(i.id)}</span><span class="killer">${esc(i.killer)}</span><span class="victim">${esc(i.victim)}</span><span class="date">${date(i.date)}</span><span class="map">${esc(i.map)}</span><span class="notes">${esc(i.notes||'No notes recorded.')}</span><span>${i.clip?`<a class="clip-icon" href="${esc(i.clip)}" target="_blank" rel="noopener">↗</a>`:''}</span><span><button class="delete-tk" data-id="${esc(i.id)}">DELETE</button></span></div>`).join('');document.querySelectorAll('.delete-tk').forEach(b=>b.onclick=()=>deleteKill(b.dataset.id))}
async function deleteKill(id){const old=incidents.find(i=>String(i.id)===String(id));if(!old)return;if(!confirm(`DELETE ${old.id}: ${old.killer} → ${old.victim}?\n\nThis cannot be undone.`))return;if(!token())return status('status','Enter your GitHub token first.','error');try{status('status',`Deleting ${id}...`,'working');const cur=await read(INCIDENT_FILE),updated=cur.data.filter(i=>String(i.id)!==String(id));const put=await fetch(`${API_BASE}/contents/${INCIDENT_FILE}`,{method:'PUT',headers:{...headers(true),'Content-Type':'application/json'},body:JSON.stringify({message:`Delete ${id}: ${old.killer} → ${old.victim}`,content:enc(updated),sha:cur.sha,branch:BRANCH})});const j=await put.json();if(!put.ok)throw Error(j.message||'GitHub delete failed.');incidents=updated;renderRecent();renderPlayers();status('status',`${id} deleted successfully.`,'success')}catch(e){status('status',e.message,'error')}}
async function addKill(){const k=$('killer').value,v=clean($('victim').value),d=$('date').value,m=$('map').value,c=$('clip').value.trim();if(!k)return status('status','Select the player who team killed.','error');if(!v)return status('status','Enter the victim name.','error');if(norm(k)===norm(v))return status('status','The killer and victim cannot be the same player.','error');if(!d)return status('status','Select a date.','error');if(!m)return status('status','Select a map.','error');if(c){try{new URL(c)}catch{return status('status','The video clip URL is not valid.','error')}}if(!token()){status('status','Enter your GitHub token first.','error');$('token').focus();return}try{$('addKill').disabled=true;status('status','Adding team kill to GitHub...','working');const cur=await read(INCIDENT_FILE),data=Array.isArray(cur.data)?cur.data:[],i={id:nextId(data),killer:k,victim:v,date:d,map:m,notes:$('notes').value.trim(),clip:c};const put=await fetch(`${API_BASE}/contents/${INCIDENT_FILE}`,{method:'PUT',headers:{...headers(true),'Content-Type':'application/json'},body:JSON.stringify({message:`Add ${i.id}: ${i.killer} → ${i.victim}`,content:enc([...data,i]),sha:cur.sha,branch:BRANCH})});const j=await put.json();if(!put.ok)throw Error(j.message||'GitHub write failed.');incidents=[...data,i];renderRecent();renderPlayers();clearForm();status('status',`${i.id} added successfully. GitHub has been updated.`,'success')}catch(e){status('status',e.message,'error')}finally{$('addKill').disabled=false}}
function clearForm(){$('killer').value='';$('victim').value='';$('date').value=new Date().toISOString().slice(0,10);$('map').value='';$('notes').value='';$('clip').value=''}function date(v){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('date').value=new Date().toISOString().slice(0,10);$('playerImage')?.addEventListener('change',updatePlayerImagePreview);loadPlayerImages();$('addPlayer').onclick=addPlayer;$('newPlayer').onkeydown=e=>{if(e.key==='Enter')addPlayer()};$('addKill').onclick=addKill;$('clearForm').onclick=()=>{clearForm();clearStatus('status')};load();