const state={incidents:[],filtered:[]},$=id=>document.getElementById(id),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),display=s=>String(s??'').trim().replace(/\s+/g,' ');
async function loadData(){try{const r=await fetch(`data/teamkills.json?v=${Date.now()}`);if(!r.ok)throw Error(`HTTP ${r.status}`);state.incidents=Array.isArray(await r.json())?await (async()=>{const r2=await fetch(`data/teamkills.json?v=${Date.now()}`);return r2.json()})():[];updateTime()}catch(e){console.error(e);state.incidents=[];$('lastUpdated').textContent='DATA UPDATE FAILED'}state.filtered=[...state.incidents];populate();render()}
function updateTime(){const d=new Date(),ds=d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}),ts=d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});$('lastUpdated').textContent=`DATA UPDATED — ${ds.toUpperCase()} ${ts}`}
function populate(){const maps=[...new Set(state.incidents.map(i=>i.map).filter(Boolean))].sort(),players=[...new Map(state.incidents.map(i=>i.killer).filter(Boolean).map(p=>[norm(p),display(p)])).values()].sort((a,b)=>a.localeCompare(b));$('mapFilter').innerHTML='<option value="">All Maps</option>'+maps.map(x=>`<option>${esc(x)}</option>`).join('');$('playerFilter').innerHTML='<option value="">All Players</option>'+players.map(x=>`<option>${esc(x)}</option>`).join('')}
function apply(){const q=norm($('searchInput').value),m=$('mapFilter').value,p=norm($('playerFilter').value);state.filtered=state.incidents.filter(i=>{const t=[i.id,i.killer,i.victim,i.date,i.map,i.notes].join(' ').toLowerCase();return(!q||t.includes(q))&&(!m||i.map===m)&&(!p||norm(i.killer)===p||norm(i.victim)===p)}).sort(sort);table()}
function sort(a,b){return String(b.date).localeCompare(String(a.date))||String(b.id).localeCompare(String(a.id))}
function counts(fn){return state.incidents.reduce((o,i)=>{const k=fn(i);if(k)o[k]=(o[k]||0)+1;return o},{})}
function storedName(key,field){const i=state.incidents.find(x=>norm(x[field])===key);return i?display(i[field]):key}
function top(c,field){const x=Object.entries(c).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0];return x?storedName(x[0],field):'—'}
function render(){const a=state.incidents,k=counts(i=>norm(i.killer)),v=counts(i=>norm(i.victim));$('totalKills').textContent=a.length;$('recordCount').textContent=`${a.length} ${a.length===1?'INCIDENT':'INCIDENTS'}`;$('playerCount').textContent=Object.keys(k).length;$('mapCount').textContent=new Set(a.map(i=>i.map).filter(Boolean)).size;$('topKiller').textContent=top(k,'killer');$('topVictim').textContent=top(v,'victim');leaderboard();table();recent()}
function leaderboard(){const a=state.incidents,k=counts(i=>norm(i.killer)),names=Object.keys(k).sort((x,y)=>k[y]-k[x]||x.localeCompare(y));$('leaderboard').innerHTML=names.length?`<div class="rank-card table-label"><div>#</div><div>PLAYER</div><div class="rank-count">TEAM KILLS</div><div class="rank-count">VICTIMS</div><div class="rank-count">VICTIMIZED</div><div class="rank-count">TK RATIO</div></div>`+names.map((n,i)=>{const kills=k[n],victims=new Set(a.filter(x=>norm(x.killer)===n).map(x=>norm(x.victim))).size,received=a.filter(x=>norm(x.killer)!==n&&norm(x.victim)===n).length,total=kills+received,ratio=total?Math.round(kills/total*100):100;return`<div class="rank-card"><div class="rank">${i+1}</div><div class="rank-name">${esc(storedName(n,'killer'))}</div><div class="rank-count"><strong>${kills}</strong></div><div class="rank-count"><strong>${victims}</strong></div><div class="rank-count"><strong>${received}</strong></div><div class="rank-count"><strong>${ratio}%</strong></div></div>`}).join(''):'<div class="empty"><p>No team killers recorded yet.</p></div>'}
function header(){return'<div class="table-head"><span>TK ID</span><span>KILLER</span><span>VICTIM</span><span>DATE</span><span>MAP</span><span>NOTES</span><span>CLIP</span></div>'}
function row(i){return`<div class="incident-row"><span class="tkid">${esc(i.id)}</span><span class="killer">${esc(display(i.killer))}</span><span class="victim">${esc(display(i.victim))}</span><span class="date">${date(i.date)}</span><span class="map">${esc(i.map)}</span><span class="notes">${esc(i.notes||'No notes recorded.')}</span><span>${i.clip?`<a class="clip-icon" href="${esc(i.clip)}" target="_blank" rel="noopener">↗</a>`:''}</span></div>`}
function table(){$('incidentTable').innerHTML=header()+state.filtered.map(row).join('');$('empty').classList.toggle('hidden',state.filtered.length!==0)}
function recent(){const a=[...state.incidents].sort(sort).slice(0,5);$('dashboardRecent').innerHTML=a.length?header()+a.map(row).join(''):'<div class="empty"><p>No incidents recorded yet.</p></div>'}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active-view',x.id===`view-${v}`));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));history.replaceState(null,'',`#${v}`)}
function date(v){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.querySelectorAll('.nav-item,.panel-link').forEach(b=>b.onclick=()=>show(b.dataset.view));$('searchInput').oninput=apply;$('mapFilter').onchange=apply;$('playerFilter').onchange=apply;$('resetFilters').onclick=()=>{$('searchInput').value='';$('mapFilter').value='';$('playerFilter').value='';apply()};show(['dashboard','leaderboard','incidents'].includes(location.hash.slice(1))?location.hash.slice(1):'dashboard');loadData();
